package Client.GUI.Admin;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

import Shared.Objednavky;
import Shared.data.Produkt;

public class pridaniProduktuFrame extends javax.swing.JFrame {

    /**
     * Creates new form pridaniProduktuFrame
     */
    public pridaniProduktuFrame() {
            initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * @throws NotBoundException
     * @throws RemoteException
     * @throws MalformedURLException
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pridaniLabel = new javax.swing.JLabel();
        nazevLabel = new javax.swing.JLabel();
        nazevField = new javax.swing.JTextField();
        cenaLabel = new javax.swing.JLabel();
        cenaField = new javax.swing.JTextField();
        aktivniLabel = new javax.swing.JLabel();
        kategorieBox = new javax.swing.JComboBox<>();
        zrusitButton = new javax.swing.JButton();
        zmenaButton = new javax.swing.JButton();
        kategorieLabel = new javax.swing.JLabel();
        aktivniBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pridaniLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pridaniLabel.setText("Přidání produktu");

        nazevLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nazevLabel.setText("Název produktu");

        cenaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cenaLabel.setText("Cena produktu");

        aktivniLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aktivniLabel.setText("Aktivní?");

        zrusitButton.setText("Zrušit");
        zrusitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zrusitButtonMouseClicked(evt);
            }
        });

        zmenaButton.setText("Přidat");
        zmenaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                    try {
                        zmenaButtonMouseClicked(evt);
                    } catch (MalformedURLException | RemoteException | NotBoundException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }

            }
        });

        kategorieLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kategorieLabel.setText("Kategorie");

        kategorieBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Menu - Příloha",
                "Menu - Nápoj", "Menu - Přídavek", "Burgery", "Burgery - Přídavek", "Nápoje", "Nápoje - Přídavek", "Ostatní" }));

        aktivniBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ne", "Ano" }));


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(nazevLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nazevField, javax.swing.GroupLayout.PREFERRED_SIZE, 357,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(zrusitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(zmenaButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(kategorieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kategorieBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pridaniLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(cenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 357,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(aktivniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(aktivniBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pridaniLabel).addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nazevField, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nazevLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kategorieBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kategorieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(aktivniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aktivniBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(zrusitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zmenaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap()));

        pack();
        System.gc();
    }// </editor-fold>

    private void zrusitButtonMouseClicked(java.awt.event.MouseEvent evt) {
        editaceProduktuFrame ed = new editaceProduktuFrame();
        this.dispose();
        ed.setVisible(true);
    }

    private void zmenaButtonMouseClicked(java.awt.event.MouseEvent evt) throws MalformedURLException, RemoteException, NotBoundException{

        Objednavky o = (Objednavky) Naming.lookup("rmi://jskola:12345/objednavka");
        Produkt p = new Produkt().setidKategorie(kategorieBox.getSelectedIndex() + 1)
                .setNazevPolozky(nazevField.getText()).setCena(Integer.parseInt(cenaField.getText()))
                .setAktivni(aktivniBox.getSelectedIndex());
        if (o.writeProdukt(p))
            System.out.println("Zápis ok");
        else
            System.out.println("Zápis neproběhl");
        editaceProduktuFrame ed = new editaceProduktuFrame();
        this.dispose();
        ed.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> aktivniBox;
    private javax.swing.JLabel aktivniLabel;
    private javax.swing.JTextField cenaField;
    private javax.swing.JLabel cenaLabel;
    private javax.swing.JComboBox<String> kategorieBox;
    private javax.swing.JLabel kategorieLabel;
    private javax.swing.JTextField nazevField;
    private javax.swing.JLabel nazevLabel;
    private javax.swing.JLabel pridaniLabel;
    private javax.swing.JButton zmenaButton;
    private javax.swing.JButton zrusitButton;
    // End of variables declaration
}
